services:
    postgres:
        image: postgres:16-alpine
        container_name: discogsdash-postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        env_file: .env
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-discogsdash}"]
            interval: 10s
            timeout: 5s
            retries: 5

    discogsdash:
        build: .
        # image: ghcr.io/rtuszik/discogsdash:latest
        container_name: discogsdash
        ports:
            - "3000:3000"
        env_file: .env
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped

volumes:
    postgres-data:
